version: "3.9" 

services:
  api:
    image: api
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/test?authSource=admin&readPreference=primary&ssl=false
      - MONGO_DATABASE=demo
      - REDIS_URI=redis:6379
    networks:
      - app_network
    external_links:
      - mongodb
      - redis
    scale: 5

  redis:
    image: redis
    networks:
      - app_network

  mongodb:
    image: mongo:4.4.3
    networks:
      - app_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - app_network 

networks:
  app_network: