serve:
	MONGO_URI="mongodb://admin:password@localhost:27017/test?authSource=admin'" \
	MONGO_DATABASE="demo" \
	RABBITMQ_URI="amqp://user:password@localhost:5672/" \
	RABBITMQ_QUEUE="rss_urls" \
	go run .